apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-local
  claimRef:
    namespace: kafka
    name: data-my-cluster-dual-role-0
  local:
    path: /mnt/storage-data/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - storage
