apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-local
  claimRef:
    namespace: minio
    name: minio
  local:
    path: /mnt/storage-data/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - storage
