apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  init-databases.sql: |
    CREATE DATABASE airflow;
    CREATE DATABASE mlflow;
    CREATE DATABASE superset;
    CREATE DATABASE grafana;
