apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  storageClassName: postgres-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
