apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
