apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-local
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
